<h1>[PROBLEM 1]</h1>

<img src="1" alt="Image Alt Text">
<h3>Here are the initial Matrixes, A and B
First we have to check the condition for two matrixes be multiplied: the number of columns of the first
matrix must be equal to the number of rows of the second matrix
In this case, the condition is satisfied</h3>



<img src="2" alt="Image Alt Text">
<h3>Here I show what would be the structure of the product(C)</h3>

<img src="3" alt="Image Alt Text">
<img src="4" alt="Image Alt Text">
<img src="5" alt="Image Alt Text">

<h3>Here I calculate the value of each C matrix element.
I do this by taking the corresponding row from matrix A  and the corresponding column from matrix B, and multiply the elements, and then sum them up.
The first row of matrix A corresponds to the first column of matrix B
So we take every element of the rows and columns and multiply it, after that, we take those products and sum.</h3>




<img src="6" alt="Image Alt Text">

<h3>This is the product. Matrix.</h3>


<h1>[PROBLEM 2]</h1>

In [340]:
import numpy as np

In [341]:
a_ndarray = np.array([[-1, 2, 3], 
                      [4, -5, 6], 
                      [7, 8, -9]])

b_ndarray = np.array([[0, 2, 1], 
                      [0, 2, -8], 
                      [2, 9, -1]])


In [342]:
# using numpy.matmul
c_ndarray = np.matmul(a_ndarray, b_ndarray)
print(c_ndarray)


[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [343]:
# using numpy.matmul but with its shortcut "@"
c_ndarray = a_ndarray @ b_ndarray
print(c_ndarray)


[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [344]:
# using numpy.dot
c_ndarray = np.dot(a_ndarray, b_ndarray)
print(c_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


<h1>[PROBLEM 3]</h1>

In [345]:
from numpy import linalg as lg

In [346]:
def row_column_product(row_elements, column_elements):
    sum = 0
    for i in range (len(row_elements)):
        sum += row_elements[i] * column_elements[i]
    
    return sum



In [347]:
row = [-1, 2, 3]
column = [0, 0, 2]
p = row_column_product(row, column)
print(p)

6


<h1>[PROBLEM 4]</h1>

In [348]:
def matrix_product(matrix_a, matrix_b):
    # matrix_b = np.transpose(matrix_b)#to swap to columns for the rows, so computing will be easier
    matrix_c = np.zeros((len(matrix_a), len(matrix_b[0])))
    for i in range (0,  len(matrix_a)):
        for j in range (0,  len(matrix_b[0])):
            col = []
            for k in matrix_b:
                col.append(k[j])
            
            matrix_c[i][j] = row_column_product(matrix_a[i],col)
    
    return matrix_c

c_ndarray = matrix_product(a_ndarray, b_ndarray)
print(c_ndarray)


[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


<h1>[PROBLEM 5]</h1>

In [349]:
def are_multipliable(matrix_a, matrix_b):
    if len(matrix_b[0])==len(matrix_a):
        return True
    else:
        return f'''The number of rows in the first matrix does not correspond to the number of columns in the second matrix
Expected {len(matrix_a)} columns for the second matrix, but got {len(matrix_b[0])} 
        '''
    
test1 = np.array([  [-1, 2, 3], 
                    [4, -5, 6], 
                    [7, 8, -9]])

test2 = np.array([  [0, 2, 1], 
                    [0, 2, -8], 
                    [2, 9, -1]])
b = are_multipliable(test1, test2)
print(b)

True


In [350]:
test3 = np.array([  [-1, 2, 3], 
                    [4, -5, 6], 
                    [7, 8, -9]])

test4 = np.array([  [0, 2], 
                    [0, 2], 
                    [2, 9]])
b = are_multipliable(test3, test4)
print(b)

The number of rows in the first matrix does not correspond to the number of columns in the second matrix
Expected 3 columns for the second matrix. But got 2 
        


<h1>[PROBLEM 6]</h1>

In [351]:
def matrix_product(matrix_a, matrix_b):
    matrix_b = np.transpose(matrix_b)#to swap to columns for the rows, so computing will be easier
    matrix_c = np.zeros((len(matrix_a), len(matrix_b)))
    for i in range (0,  len(matrix_a)):
        for j in range (0,  len(matrix_b)):
            matrix_c[i][j] = row_column_product(matrix_a[i],matrix_b[j])
    
    return matrix_c

c_ndarray = matrix_product(a_ndarray, b_ndarray)
print(c_ndarray)


[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]
